services:
  myip:
    container_name: myip
    image: olafrv/myip:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${MYIP_PORT}:${MYIP_PORT}"
    restart: always
    volumes:
      - ./dbs:/usr/src/app/dbs
      - "${MYIP_SSL_KEY}:/usr/src/app/letsencrypt/privkey.pem"
      - "${MYIP_SSL_FULLCHAIN}:/usr/src/app/letsencrypt/fullchain.pem"
    environment:
      - NODE_ENV=production

