services:
  myip:
    container_name: myip
    image: olafrv/myip:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # MYIP_DB_REFRESH_ONLY must be an integer, 1 for true, 0 for false
      - MYIP_DB_REFRESH_ONLY=${MYIP_DB_REFRESH_ONLY}
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "${MYIP_PORT}:${MYIP_PORT}"
    restart: always
    volumes:
      - ./dbs:/usr/src/app/dbs
      - "${MYIP_SSL_KEY}:/usr/src/app/letsencrypt/privkey.pem"
      - "${MYIP_SSL_FULLCHAIN}:/usr/src/app/letsencrypt/fullchain.pem"

