services:
  myip:
    container_name: myip
    image: olafrv/myip:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${MYIP_PORT}:${MYIP_PORT}"
    restart: always
    volumes:
      - ./dbs:/usr/src/app/dbs
    environment:
      - NODE_ENV=production

